# Generated by Django 4.2 on 2023-05-22 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_bookmarkpost_bookmarkcategory_category_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='bookmark',
        ),
        migrations.AlterField(
            model_name='bookmarkcategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
