# Generated by Django 4.2 on 2023-05-22 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_category_bookmark_alter_bookmarkcategory_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='bookmarkpost',
            name='obj',
        ),
        migrations.RemoveField(
            model_name='bookmarkpost',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookmarkCategory',
        ),
        migrations.DeleteModel(
            name='BookmarkPost',
        ),
    ]
