# Generated by Django 4.2 on 2023-05-22 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_saved_remove_bookmarkpost_obj_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saved',
            old_name='product',
            new_name='post',
        ),
    ]
