# Generated by Django 4.2 on 2023-05-22 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_bookmark_delete_saved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
