# Generated by Django 4.2 on 2023-05-26 00:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='favourites',
        ),
        migrations.AddField(
            model_name='post',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
