# Generated by Django 4.0 on 2023-05-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_category_favourites_post_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exclude_posts',
            field=models.TextField(blank=True),
        ),
    ]
